<?php View::content() ?>
<?php if ($config['application']['production']): ?>
    
<?php else: ?>  
    <?php echo Form::open("","POST",'class="form-horizontal" role="form"') ?>
    <?php foreach ($db_configuracion as $key => $value): ?>
        <h2><?php echo ucfirst($key) ?></h2>
        <?php foreach ($value as $k => $v): ?>
              <div class="form-group">
                <label for="<?php echo $key ?>" class="col-sm-2 control-label"><?php echo ucfirst($k) ?></label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" maxlength="20" name="<?php echo $key.'['.$k.']' ?>" id="<?php echo $k.'_'.$key ?>" placeholder="<?php echo ucfirst($k) ?>" value="<?php echo $db_configuracion[$key][$k]?>">
                </div>
              </div>
        <?php endforeach ?>
        <?php try {
             if ($configurer::factory($key)->connect($db_configuracion[$key])): 
                 echo Html::link("index/control_usuario/$key","Crear Control de Usuarios","class='btn btn-default pull-right'");
                 echo '<div class="clearfix"></div>';
             endif ;
        } catch (Exception $e) {
            Flash::error($e->getMessage());
        } ?>
        
    <?php endforeach ?>
    <hr>
    <?php echo Form::submit("Hecho","class='btn btn-default pull-right'") ?>
    <div class='clearfix '></div>
    <?php echo Form::close() ?>
<?php endif ?>