<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Error 404</title>
    <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/style.css" />
    <?php Tag::css("bootstrap/bootstrap.min") ?>
    <?php echo Html::includeCss() ?>
</head>
<body>
    <div style="text-align: center; margin: 50px; font-size: 12pt; background-color: transparent; font-family: Lucida Grande, Verdana, Sans-serif;">
        <table align="center" id="content" class="jumbotron">
            <tbody>
                <tr>
                    <td>
                        <a href="http://www.kumbiaphp.com"></a>
                    </td>
                    <td class="well">
                        <h1>ERROR 404 <br><small>Página no encontrada</small>  
                        </h1>
                         <a href="javascript:history.back(1)">Volver Atrás</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>
